name: Deploy

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:


jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Make envfile
        run: |
          touch .env.production
          echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> .env.production
          echo POSTGRES_DB=${{ secrets.POSTGRES_DB }} >> .env.production
          echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env.production
          echo BOT_TOKEN=${{ secrets.BOT_TOKEN }} >> .env.production
          cat .env.production

      - name: Build Docker Images
        run: docker-compose build  --no-cache

      - name: Run containtes
        run: docker-compose -f docker-compose-prod.yml up -d
